export const ITEM_REQUEST = 'ITEM_REQUEST'
export const GROUP_REQUEST = 'GROUP_REQUEST'
export const ADD_ITEM = 'ADD_ITEM'
export const ADD_GROUP = 'ADD_GROUP'
export const GET_ITEMS = 'GET_ITEMS'
export const GET_GROUPS = 'GET_GROUPS'
